package com.anand_atm.common;

public class Constant {

	public static String GET_LOGIN_DATA = "SELECT * FROM USER WHERE USERNAME = :USERNAME AND PASSWORD = :PASSWORD ";
	
	public static String GET_ALL_DTH_NUMBER = "SELECT *, DATEDIFF(DATE_ADD(RECHARGEDATE,INTERVAL VALADITY DAY),CURRENT_DATE) AS LEFTDAYS FROM DTH ORDER BY LEFTDAYS";
	
	public static String GET_ALL_MOBILE_NUMBER = "SELECT *, DATEDIFF(DATE_ADD(RECHARGEDATE,INTERVAL VALADITY DAY),CURRENT_DATE) AS LEFTDAYS FROM MOBILE ORDER BY LEFTDAYS";
	
	public static String INSERT_NEW_DTH = "INSERT INTO DTH (DTHNUMBER, MOBILENUMBER, ALTNUMBER, RECHARGEDATE, NETWORK, PAYMENT, USERNAME, VALADITY, AMOUNT) VALUES (:DTHNUMBER, :MOBILENUMBER, :ALTNUMBER, now(), :NETWORK, :PAYMENT, :USERNAME, :VALADITY, :AMOUNT)";
	
	public static String INSERT_NEW_MOBILE = "INSERT INTO MOBILE (MOBILENUMBER, ALTNUMBER, NETWORK, USERNAME, RECHARGEDATE, AMOUNT, PAYMENT, VALADITY) VALUES (:MOBILENUMBER, :ALTNUMBER, :NETWORK, :USERNAME, now(), :AMOUNT, :PAYMENT, :VALADITY)";

	public static String UPDATE_DTH = "UPDATE DTH SET DTHNUMBER = :DTHNUMBER, MOBILENUMBER = :MOBILENUMBER, ALTNUMBER= :ALTNUMBER, NETWORK= :NETWORK, PAYMENT = :PAYMENT,USERNAME = :USERNAME, VALADITY = :VALADITY, AMOUNT = :AMOUNT WHERE ID = :ID";
	
	public static String UPDATE_MOBILE = "UPDATE MOBILE SET MOBILENUMBER = :MOBILENUMBER, ALTNUMBER= :ALTNUMBER, NETWORK= :NETWORK, PAYMENT = :PAYMENT,USERNAME = :USERNAME, VALADITY = :VALADITY, AMOUNT = :AMOUNT WHERE ID = :ID";

}
